// Generated by gencpp from file hero_common/Encoder.msg
// DO NOT EDIT!


#ifndef HERO_COMMON_MESSAGE_ENCODER_H
#define HERO_COMMON_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace hero_common
{
template <class ContainerAllocator>
struct Encoder_
{
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
    : header()
    , left_ticks(0.0)
    , right_ticks(0.0)
    , left_diff(0.0)
    , right_diff(0.0)
    , left_dist(0.0)
    , right_dist(0.0)
    , timestep(0.0)
    , left_speed(0.0)
    , right_speed(0.0)
    , left_speed_filtered(0.0)
    , right_speed_filtered(0.0)  {
    }
  Encoder_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_ticks(0.0)
    , right_ticks(0.0)
    , left_diff(0.0)
    , right_diff(0.0)
    , left_dist(0.0)
    , right_dist(0.0)
    , timestep(0.0)
    , left_speed(0.0)
    , right_speed(0.0)
    , left_speed_filtered(0.0)
    , right_speed_filtered(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _left_ticks_type;
  _left_ticks_type left_ticks;

   typedef double _right_ticks_type;
  _right_ticks_type right_ticks;

   typedef double _left_diff_type;
  _left_diff_type left_diff;

   typedef double _right_diff_type;
  _right_diff_type right_diff;

   typedef double _left_dist_type;
  _left_dist_type left_dist;

   typedef double _right_dist_type;
  _right_dist_type right_dist;

   typedef double _timestep_type;
  _timestep_type timestep;

   typedef double _left_speed_type;
  _left_speed_type left_speed;

   typedef double _right_speed_type;
  _right_speed_type right_speed;

   typedef double _left_speed_filtered_type;
  _left_speed_filtered_type left_speed_filtered;

   typedef double _right_speed_filtered_type;
  _right_speed_filtered_type right_speed_filtered;





  typedef boost::shared_ptr< ::hero_common::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hero_common::Encoder_<ContainerAllocator> const> ConstPtr;

}; // struct Encoder_

typedef ::hero_common::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::hero_common::Encoder > EncoderPtr;
typedef boost::shared_ptr< ::hero_common::Encoder const> EncoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hero_common::Encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hero_common::Encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hero_common::Encoder_<ContainerAllocator1> & lhs, const ::hero_common::Encoder_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left_ticks == rhs.left_ticks &&
    lhs.right_ticks == rhs.right_ticks &&
    lhs.left_diff == rhs.left_diff &&
    lhs.right_diff == rhs.right_diff &&
    lhs.left_dist == rhs.left_dist &&
    lhs.right_dist == rhs.right_dist &&
    lhs.timestep == rhs.timestep &&
    lhs.left_speed == rhs.left_speed &&
    lhs.right_speed == rhs.right_speed &&
    lhs.left_speed_filtered == rhs.left_speed_filtered &&
    lhs.right_speed_filtered == rhs.right_speed_filtered;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hero_common::Encoder_<ContainerAllocator1> & lhs, const ::hero_common::Encoder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hero_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hero_common::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_common::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_common::Encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_common::Encoder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_common::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_common::Encoder_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hero_common::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5586cdbae9b740afc6a1f403a2d7dde";
  }

  static const char* value(const ::hero_common::Encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5586cdbae9b740aULL;
  static const uint64_t static_value2 = 0xfc6a1f403a2d7ddeULL;
};

template<class ContainerAllocator>
struct DataType< ::hero_common::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hero_common/Encoder";
  }

  static const char* value(const ::hero_common::Encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hero_common::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 left_ticks\n"
"float64 right_ticks\n"
"float64 left_diff\n"
"float64 right_diff\n"
"float64 left_dist\n"
"float64 right_dist\n"
"float64 timestep\n"
"float64 left_speed\n"
"float64 right_speed\n"
"float64 left_speed_filtered\n"
"float64 right_speed_filtered\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::hero_common::Encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hero_common::Encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_ticks);
      stream.next(m.right_ticks);
      stream.next(m.left_diff);
      stream.next(m.right_diff);
      stream.next(m.left_dist);
      stream.next(m.right_dist);
      stream.next(m.timestep);
      stream.next(m.left_speed);
      stream.next(m.right_speed);
      stream.next(m.left_speed_filtered);
      stream.next(m.right_speed_filtered);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hero_common::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hero_common::Encoder_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_ticks: ";
    Printer<double>::stream(s, indent + "  ", v.left_ticks);
    s << indent << "right_ticks: ";
    Printer<double>::stream(s, indent + "  ", v.right_ticks);
    s << indent << "left_diff: ";
    Printer<double>::stream(s, indent + "  ", v.left_diff);
    s << indent << "right_diff: ";
    Printer<double>::stream(s, indent + "  ", v.right_diff);
    s << indent << "left_dist: ";
    Printer<double>::stream(s, indent + "  ", v.left_dist);
    s << indent << "right_dist: ";
    Printer<double>::stream(s, indent + "  ", v.right_dist);
    s << indent << "timestep: ";
    Printer<double>::stream(s, indent + "  ", v.timestep);
    s << indent << "left_speed: ";
    Printer<double>::stream(s, indent + "  ", v.left_speed);
    s << indent << "right_speed: ";
    Printer<double>::stream(s, indent + "  ", v.right_speed);
    s << indent << "left_speed_filtered: ";
    Printer<double>::stream(s, indent + "  ", v.left_speed_filtered);
    s << indent << "right_speed_filtered: ";
    Printer<double>::stream(s, indent + "  ", v.right_speed_filtered);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERO_COMMON_MESSAGE_ENCODER_H
