// Generated by gencpp from file hero_common/SetFrequency.msg
// DO NOT EDIT!


#ifndef HERO_COMMON_MESSAGE_SETFREQUENCY_H
#define HERO_COMMON_MESSAGE_SETFREQUENCY_H

#include <ros/service_traits.h>


#include <hero_common/SetFrequencyRequest.h>
#include <hero_common/SetFrequencyResponse.h>


namespace hero_common
{

struct SetFrequency
{

typedef SetFrequencyRequest Request;
typedef SetFrequencyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFrequency
} // namespace hero_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hero_common::SetFrequency > {
  static const char* value()
  {
    return "ff3ae8a6187feadac85089456faed43f";
  }

  static const char* value(const ::hero_common::SetFrequency&) { return value(); }
};

template<>
struct DataType< ::hero_common::SetFrequency > {
  static const char* value()
  {
    return "hero_common/SetFrequency";
  }

  static const char* value(const ::hero_common::SetFrequency&) { return value(); }
};


// service_traits::MD5Sum< ::hero_common::SetFrequencyRequest> should match
// service_traits::MD5Sum< ::hero_common::SetFrequency >
template<>
struct MD5Sum< ::hero_common::SetFrequencyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hero_common::SetFrequency >::value();
  }
  static const char* value(const ::hero_common::SetFrequencyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hero_common::SetFrequencyRequest> should match
// service_traits::DataType< ::hero_common::SetFrequency >
template<>
struct DataType< ::hero_common::SetFrequencyRequest>
{
  static const char* value()
  {
    return DataType< ::hero_common::SetFrequency >::value();
  }
  static const char* value(const ::hero_common::SetFrequencyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hero_common::SetFrequencyResponse> should match
// service_traits::MD5Sum< ::hero_common::SetFrequency >
template<>
struct MD5Sum< ::hero_common::SetFrequencyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hero_common::SetFrequency >::value();
  }
  static const char* value(const ::hero_common::SetFrequencyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hero_common::SetFrequencyResponse> should match
// service_traits::DataType< ::hero_common::SetFrequency >
template<>
struct DataType< ::hero_common::SetFrequencyResponse>
{
  static const char* value()
  {
    return DataType< ::hero_common::SetFrequency >::value();
  }
  static const char* value(const ::hero_common::SetFrequencyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HERO_COMMON_MESSAGE_SETFREQUENCY_H
