// Generated by gencpp from file hero_common/SetFrequencyRequest.msg
// DO NOT EDIT!


#ifndef HERO_COMMON_MESSAGE_SETFREQUENCYREQUEST_H
#define HERO_COMMON_MESSAGE_SETFREQUENCYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hero_common
{
template <class ContainerAllocator>
struct SetFrequencyRequest_
{
  typedef SetFrequencyRequest_<ContainerAllocator> Type;

  SetFrequencyRequest_()
    : frequency(0.0)  {
    }
  SetFrequencyRequest_(const ContainerAllocator& _alloc)
    : frequency(0.0)  {
  (void)_alloc;
    }



   typedef double _frequency_type;
  _frequency_type frequency;





  typedef boost::shared_ptr< ::hero_common::SetFrequencyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hero_common::SetFrequencyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetFrequencyRequest_

typedef ::hero_common::SetFrequencyRequest_<std::allocator<void> > SetFrequencyRequest;

typedef boost::shared_ptr< ::hero_common::SetFrequencyRequest > SetFrequencyRequestPtr;
typedef boost::shared_ptr< ::hero_common::SetFrequencyRequest const> SetFrequencyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hero_common::SetFrequencyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hero_common::SetFrequencyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hero_common::SetFrequencyRequest_<ContainerAllocator1> & lhs, const ::hero_common::SetFrequencyRequest_<ContainerAllocator2> & rhs)
{
  return lhs.frequency == rhs.frequency;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hero_common::SetFrequencyRequest_<ContainerAllocator1> & lhs, const ::hero_common::SetFrequencyRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hero_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hero_common::SetFrequencyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_common::SetFrequencyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_common::SetFrequencyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_common::SetFrequencyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_common::SetFrequencyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_common::SetFrequencyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hero_common::SetFrequencyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49c627ecd142a5c42775297233551ead";
  }

  static const char* value(const ::hero_common::SetFrequencyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49c627ecd142a5c4ULL;
  static const uint64_t static_value2 = 0x2775297233551eadULL;
};

template<class ContainerAllocator>
struct DataType< ::hero_common::SetFrequencyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hero_common/SetFrequencyRequest";
  }

  static const char* value(const ::hero_common::SetFrequencyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hero_common::SetFrequencyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 frequency # loop-frequency in Hz\n"
;
  }

  static const char* value(const ::hero_common::SetFrequencyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hero_common::SetFrequencyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frequency);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetFrequencyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hero_common::SetFrequencyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hero_common::SetFrequencyRequest_<ContainerAllocator>& v)
  {
    s << indent << "frequency: ";
    Printer<double>::stream(s, indent + "  ", v.frequency);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERO_COMMON_MESSAGE_SETFREQUENCYREQUEST_H
