// Generated by gencpp from file hero_common/SetIRCalibration.msg
// DO NOT EDIT!


#ifndef HERO_COMMON_MESSAGE_SETIRCALIBRATION_H
#define HERO_COMMON_MESSAGE_SETIRCALIBRATION_H

#include <ros/service_traits.h>


#include <hero_common/SetIRCalibrationRequest.h>
#include <hero_common/SetIRCalibrationResponse.h>


namespace hero_common
{

struct SetIRCalibration
{

typedef SetIRCalibrationRequest Request;
typedef SetIRCalibrationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetIRCalibration
} // namespace hero_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hero_common::SetIRCalibration > {
  static const char* value()
  {
    return "fc55fd34ad2ef676815ba2e14521ac73";
  }

  static const char* value(const ::hero_common::SetIRCalibration&) { return value(); }
};

template<>
struct DataType< ::hero_common::SetIRCalibration > {
  static const char* value()
  {
    return "hero_common/SetIRCalibration";
  }

  static const char* value(const ::hero_common::SetIRCalibration&) { return value(); }
};


// service_traits::MD5Sum< ::hero_common::SetIRCalibrationRequest> should match
// service_traits::MD5Sum< ::hero_common::SetIRCalibration >
template<>
struct MD5Sum< ::hero_common::SetIRCalibrationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hero_common::SetIRCalibration >::value();
  }
  static const char* value(const ::hero_common::SetIRCalibrationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hero_common::SetIRCalibrationRequest> should match
// service_traits::DataType< ::hero_common::SetIRCalibration >
template<>
struct DataType< ::hero_common::SetIRCalibrationRequest>
{
  static const char* value()
  {
    return DataType< ::hero_common::SetIRCalibration >::value();
  }
  static const char* value(const ::hero_common::SetIRCalibrationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hero_common::SetIRCalibrationResponse> should match
// service_traits::MD5Sum< ::hero_common::SetIRCalibration >
template<>
struct MD5Sum< ::hero_common::SetIRCalibrationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hero_common::SetIRCalibration >::value();
  }
  static const char* value(const ::hero_common::SetIRCalibrationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hero_common::SetIRCalibrationResponse> should match
// service_traits::DataType< ::hero_common::SetIRCalibration >
template<>
struct DataType< ::hero_common::SetIRCalibrationResponse>
{
  static const char* value()
  {
    return DataType< ::hero_common::SetIRCalibration >::value();
  }
  static const char* value(const ::hero_common::SetIRCalibrationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HERO_COMMON_MESSAGE_SETIRCALIBRATION_H
