// Generated by gencpp from file hero_common/SetIRCalibrationRequest.msg
// DO NOT EDIT!


#ifndef HERO_COMMON_MESSAGE_SETIRCALIBRATIONREQUEST_H
#define HERO_COMMON_MESSAGE_SETIRCALIBRATIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hero_common
{
template <class ContainerAllocator>
struct SetIRCalibrationRequest_
{
  typedef SetIRCalibrationRequest_<ContainerAllocator> Type;

  SetIRCalibrationRequest_()
    : IR0(0.0)
    , IR1(0.0)
    , IR2(0.0)
    , IR3(0.0)
    , IR4(0.0)
    , IR5(0.0)
    , IR6(0.0)
    , IR7(0.0)  {
    }
  SetIRCalibrationRequest_(const ContainerAllocator& _alloc)
    : IR0(0.0)
    , IR1(0.0)
    , IR2(0.0)
    , IR3(0.0)
    , IR4(0.0)
    , IR5(0.0)
    , IR6(0.0)
    , IR7(0.0)  {
  (void)_alloc;
    }



   typedef double _IR0_type;
  _IR0_type IR0;

   typedef double _IR1_type;
  _IR1_type IR1;

   typedef double _IR2_type;
  _IR2_type IR2;

   typedef double _IR3_type;
  _IR3_type IR3;

   typedef double _IR4_type;
  _IR4_type IR4;

   typedef double _IR5_type;
  _IR5_type IR5;

   typedef double _IR6_type;
  _IR6_type IR6;

   typedef double _IR7_type;
  _IR7_type IR7;





  typedef boost::shared_ptr< ::hero_common::SetIRCalibrationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hero_common::SetIRCalibrationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetIRCalibrationRequest_

typedef ::hero_common::SetIRCalibrationRequest_<std::allocator<void> > SetIRCalibrationRequest;

typedef boost::shared_ptr< ::hero_common::SetIRCalibrationRequest > SetIRCalibrationRequestPtr;
typedef boost::shared_ptr< ::hero_common::SetIRCalibrationRequest const> SetIRCalibrationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hero_common::SetIRCalibrationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hero_common::SetIRCalibrationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hero_common::SetIRCalibrationRequest_<ContainerAllocator1> & lhs, const ::hero_common::SetIRCalibrationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.IR0 == rhs.IR0 &&
    lhs.IR1 == rhs.IR1 &&
    lhs.IR2 == rhs.IR2 &&
    lhs.IR3 == rhs.IR3 &&
    lhs.IR4 == rhs.IR4 &&
    lhs.IR5 == rhs.IR5 &&
    lhs.IR6 == rhs.IR6 &&
    lhs.IR7 == rhs.IR7;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hero_common::SetIRCalibrationRequest_<ContainerAllocator1> & lhs, const ::hero_common::SetIRCalibrationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hero_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hero_common::SetIRCalibrationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_common::SetIRCalibrationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_common::SetIRCalibrationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_common::SetIRCalibrationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_common::SetIRCalibrationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_common::SetIRCalibrationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hero_common::SetIRCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27748d949ad62e65750ad22074426005";
  }

  static const char* value(const ::hero_common::SetIRCalibrationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27748d949ad62e65ULL;
  static const uint64_t static_value2 = 0x750ad22074426005ULL;
};

template<class ContainerAllocator>
struct DataType< ::hero_common::SetIRCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hero_common/SetIRCalibrationRequest";
  }

  static const char* value(const ::hero_common::SetIRCalibrationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hero_common::SetIRCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 IR0 # alpha value for IR0\n"
"float64 IR1 # alpha value for IR1\n"
"float64 IR2 # alpha value for IR2\n"
"float64 IR3 # alpha value for IR3\n"
"float64 IR4 # alpha value for IR4\n"
"float64 IR5 # alpha value for IR5\n"
"float64 IR6 # alpha value for IR6\n"
"float64 IR7 # alpha value for IR7\n"
;
  }

  static const char* value(const ::hero_common::SetIRCalibrationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hero_common::SetIRCalibrationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.IR0);
      stream.next(m.IR1);
      stream.next(m.IR2);
      stream.next(m.IR3);
      stream.next(m.IR4);
      stream.next(m.IR5);
      stream.next(m.IR6);
      stream.next(m.IR7);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetIRCalibrationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hero_common::SetIRCalibrationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hero_common::SetIRCalibrationRequest_<ContainerAllocator>& v)
  {
    s << indent << "IR0: ";
    Printer<double>::stream(s, indent + "  ", v.IR0);
    s << indent << "IR1: ";
    Printer<double>::stream(s, indent + "  ", v.IR1);
    s << indent << "IR2: ";
    Printer<double>::stream(s, indent + "  ", v.IR2);
    s << indent << "IR3: ";
    Printer<double>::stream(s, indent + "  ", v.IR3);
    s << indent << "IR4: ";
    Printer<double>::stream(s, indent + "  ", v.IR4);
    s << indent << "IR5: ";
    Printer<double>::stream(s, indent + "  ", v.IR5);
    s << indent << "IR6: ";
    Printer<double>::stream(s, indent + "  ", v.IR6);
    s << indent << "IR7: ";
    Printer<double>::stream(s, indent + "  ", v.IR7);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERO_COMMON_MESSAGE_SETIRCALIBRATIONREQUEST_H
