// Generated by gencpp from file hero_common/SetMotorRequest.msg
// DO NOT EDIT!


#ifndef HERO_COMMON_MESSAGE_SETMOTORREQUEST_H
#define HERO_COMMON_MESSAGE_SETMOTORREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hero_common
{
template <class ContainerAllocator>
struct SetMotorRequest_
{
  typedef SetMotorRequest_<ContainerAllocator> Type;

  SetMotorRequest_()
    : left_motor_pwm(0)
    , right_motor_pwm(0)  {
    }
  SetMotorRequest_(const ContainerAllocator& _alloc)
    : left_motor_pwm(0)
    , right_motor_pwm(0)  {
  (void)_alloc;
    }



   typedef int16_t _left_motor_pwm_type;
  _left_motor_pwm_type left_motor_pwm;

   typedef int16_t _right_motor_pwm_type;
  _right_motor_pwm_type right_motor_pwm;





  typedef boost::shared_ptr< ::hero_common::SetMotorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hero_common::SetMotorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetMotorRequest_

typedef ::hero_common::SetMotorRequest_<std::allocator<void> > SetMotorRequest;

typedef boost::shared_ptr< ::hero_common::SetMotorRequest > SetMotorRequestPtr;
typedef boost::shared_ptr< ::hero_common::SetMotorRequest const> SetMotorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hero_common::SetMotorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hero_common::SetMotorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hero_common::SetMotorRequest_<ContainerAllocator1> & lhs, const ::hero_common::SetMotorRequest_<ContainerAllocator2> & rhs)
{
  return lhs.left_motor_pwm == rhs.left_motor_pwm &&
    lhs.right_motor_pwm == rhs.right_motor_pwm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hero_common::SetMotorRequest_<ContainerAllocator1> & lhs, const ::hero_common::SetMotorRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hero_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hero_common::SetMotorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_common::SetMotorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_common::SetMotorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_common::SetMotorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_common::SetMotorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_common::SetMotorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hero_common::SetMotorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "44d4249d207ce6a89de3d72080e4d0b5";
  }

  static const char* value(const ::hero_common::SetMotorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x44d4249d207ce6a8ULL;
  static const uint64_t static_value2 = 0x9de3d72080e4d0b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::hero_common::SetMotorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hero_common/SetMotorRequest";
  }

  static const char* value(const ::hero_common::SetMotorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hero_common::SetMotorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 left_motor_pwm # motor deadzone pwm\n"
"int16 right_motor_pwm # motor deadzone pwm\n"
;
  }

  static const char* value(const ::hero_common::SetMotorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hero_common::SetMotorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_motor_pwm);
      stream.next(m.right_motor_pwm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetMotorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hero_common::SetMotorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hero_common::SetMotorRequest_<ContainerAllocator>& v)
  {
    s << indent << "left_motor_pwm: ";
    Printer<int16_t>::stream(s, indent + "  ", v.left_motor_pwm);
    s << indent << "right_motor_pwm: ";
    Printer<int16_t>::stream(s, indent + "  ", v.right_motor_pwm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERO_COMMON_MESSAGE_SETMOTORREQUEST_H
