// Generated by gencpp from file hero_common/SetMotor.msg
// DO NOT EDIT!


#ifndef HERO_COMMON_MESSAGE_SETMOTOR_H
#define HERO_COMMON_MESSAGE_SETMOTOR_H

#include <ros/service_traits.h>


#include <hero_common/SetMotorRequest.h>
#include <hero_common/SetMotorResponse.h>


namespace hero_common
{

struct SetMotor
{

typedef SetMotorRequest Request;
typedef SetMotorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMotor
} // namespace hero_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hero_common::SetMotor > {
  static const char* value()
  {
    return "07e32bced0fc14456815cdd097819b89";
  }

  static const char* value(const ::hero_common::SetMotor&) { return value(); }
};

template<>
struct DataType< ::hero_common::SetMotor > {
  static const char* value()
  {
    return "hero_common/SetMotor";
  }

  static const char* value(const ::hero_common::SetMotor&) { return value(); }
};


// service_traits::MD5Sum< ::hero_common::SetMotorRequest> should match
// service_traits::MD5Sum< ::hero_common::SetMotor >
template<>
struct MD5Sum< ::hero_common::SetMotorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hero_common::SetMotor >::value();
  }
  static const char* value(const ::hero_common::SetMotorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hero_common::SetMotorRequest> should match
// service_traits::DataType< ::hero_common::SetMotor >
template<>
struct DataType< ::hero_common::SetMotorRequest>
{
  static const char* value()
  {
    return DataType< ::hero_common::SetMotor >::value();
  }
  static const char* value(const ::hero_common::SetMotorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hero_common::SetMotorResponse> should match
// service_traits::MD5Sum< ::hero_common::SetMotor >
template<>
struct MD5Sum< ::hero_common::SetMotorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hero_common::SetMotor >::value();
  }
  static const char* value(const ::hero_common::SetMotorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hero_common::SetMotorResponse> should match
// service_traits::DataType< ::hero_common::SetMotor >
template<>
struct DataType< ::hero_common::SetMotorResponse>
{
  static const char* value()
  {
    return DataType< ::hero_common::SetMotor >::value();
  }
  static const char* value(const ::hero_common::SetMotorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HERO_COMMON_MESSAGE_SETMOTOR_H
