// Generated by gencpp from file hero_common/SetOdomRequest.msg
// DO NOT EDIT!


#ifndef HERO_COMMON_MESSAGE_SETODOMREQUEST_H
#define HERO_COMMON_MESSAGE_SETODOMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hero_common
{
template <class ContainerAllocator>
struct SetOdomRequest_
{
  typedef SetOdomRequest_<ContainerAllocator> Type;

  SetOdomRequest_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
    }
  SetOdomRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::hero_common::SetOdomRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hero_common::SetOdomRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetOdomRequest_

typedef ::hero_common::SetOdomRequest_<std::allocator<void> > SetOdomRequest;

typedef boost::shared_ptr< ::hero_common::SetOdomRequest > SetOdomRequestPtr;
typedef boost::shared_ptr< ::hero_common::SetOdomRequest const> SetOdomRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hero_common::SetOdomRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hero_common::SetOdomRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hero_common::SetOdomRequest_<ContainerAllocator1> & lhs, const ::hero_common::SetOdomRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hero_common::SetOdomRequest_<ContainerAllocator1> & lhs, const ::hero_common::SetOdomRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hero_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hero_common::SetOdomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_common::SetOdomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_common::SetOdomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_common::SetOdomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_common::SetOdomRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_common::SetOdomRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hero_common::SetOdomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "938fa65709584ad8e77d238529be13b8";
  }

  static const char* value(const ::hero_common::SetOdomRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x938fa65709584ad8ULL;
  static const uint64_t static_value2 = 0xe77d238529be13b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::hero_common::SetOdomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hero_common/SetOdomRequest";
  }

  static const char* value(const ::hero_common::SetOdomRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hero_common::SetOdomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x # proportional term\n"
"float64 y # intergrative term\n"
"float64 theta # derivative term\n"
;
  }

  static const char* value(const ::hero_common::SetOdomRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hero_common::SetOdomRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetOdomRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hero_common::SetOdomRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hero_common::SetOdomRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERO_COMMON_MESSAGE_SETODOMREQUEST_H
