// Generated by gencpp from file hero_common/SetOdom.msg
// DO NOT EDIT!


#ifndef HERO_COMMON_MESSAGE_SETODOM_H
#define HERO_COMMON_MESSAGE_SETODOM_H

#include <ros/service_traits.h>


#include <hero_common/SetOdomRequest.h>
#include <hero_common/SetOdomResponse.h>


namespace hero_common
{

struct SetOdom
{

typedef SetOdomRequest Request;
typedef SetOdomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetOdom
} // namespace hero_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hero_common::SetOdom > {
  static const char* value()
  {
    return "4ed90569b1afd039b963e42a12637d2b";
  }

  static const char* value(const ::hero_common::SetOdom&) { return value(); }
};

template<>
struct DataType< ::hero_common::SetOdom > {
  static const char* value()
  {
    return "hero_common/SetOdom";
  }

  static const char* value(const ::hero_common::SetOdom&) { return value(); }
};


// service_traits::MD5Sum< ::hero_common::SetOdomRequest> should match
// service_traits::MD5Sum< ::hero_common::SetOdom >
template<>
struct MD5Sum< ::hero_common::SetOdomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hero_common::SetOdom >::value();
  }
  static const char* value(const ::hero_common::SetOdomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hero_common::SetOdomRequest> should match
// service_traits::DataType< ::hero_common::SetOdom >
template<>
struct DataType< ::hero_common::SetOdomRequest>
{
  static const char* value()
  {
    return DataType< ::hero_common::SetOdom >::value();
  }
  static const char* value(const ::hero_common::SetOdomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hero_common::SetOdomResponse> should match
// service_traits::MD5Sum< ::hero_common::SetOdom >
template<>
struct MD5Sum< ::hero_common::SetOdomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hero_common::SetOdom >::value();
  }
  static const char* value(const ::hero_common::SetOdomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hero_common::SetOdomResponse> should match
// service_traits::DataType< ::hero_common::SetOdom >
template<>
struct DataType< ::hero_common::SetOdomResponse>
{
  static const char* value()
  {
    return DataType< ::hero_common::SetOdom >::value();
  }
  static const char* value(const ::hero_common::SetOdomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HERO_COMMON_MESSAGE_SETODOM_H
