// Generated by gencpp from file hero_common/SetPID.msg
// DO NOT EDIT!


#ifndef HERO_COMMON_MESSAGE_SETPID_H
#define HERO_COMMON_MESSAGE_SETPID_H

#include <ros/service_traits.h>


#include <hero_common/SetPIDRequest.h>
#include <hero_common/SetPIDResponse.h>


namespace hero_common
{

struct SetPID
{

typedef SetPIDRequest Request;
typedef SetPIDResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPID
} // namespace hero_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hero_common::SetPID > {
  static const char* value()
  {
    return "69c16eccc66fd6b477afb5e5500b4b47";
  }

  static const char* value(const ::hero_common::SetPID&) { return value(); }
};

template<>
struct DataType< ::hero_common::SetPID > {
  static const char* value()
  {
    return "hero_common/SetPID";
  }

  static const char* value(const ::hero_common::SetPID&) { return value(); }
};


// service_traits::MD5Sum< ::hero_common::SetPIDRequest> should match
// service_traits::MD5Sum< ::hero_common::SetPID >
template<>
struct MD5Sum< ::hero_common::SetPIDRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hero_common::SetPID >::value();
  }
  static const char* value(const ::hero_common::SetPIDRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hero_common::SetPIDRequest> should match
// service_traits::DataType< ::hero_common::SetPID >
template<>
struct DataType< ::hero_common::SetPIDRequest>
{
  static const char* value()
  {
    return DataType< ::hero_common::SetPID >::value();
  }
  static const char* value(const ::hero_common::SetPIDRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hero_common::SetPIDResponse> should match
// service_traits::MD5Sum< ::hero_common::SetPID >
template<>
struct MD5Sum< ::hero_common::SetPIDResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hero_common::SetPID >::value();
  }
  static const char* value(const ::hero_common::SetPIDResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hero_common::SetPIDResponse> should match
// service_traits::DataType< ::hero_common::SetPID >
template<>
struct DataType< ::hero_common::SetPIDResponse>
{
  static const char* value()
  {
    return DataType< ::hero_common::SetPID >::value();
  }
  static const char* value(const ::hero_common::SetPIDResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HERO_COMMON_MESSAGE_SETPID_H
