// Generated by gencpp from file hero_common/SetPIDRequest.msg
// DO NOT EDIT!


#ifndef HERO_COMMON_MESSAGE_SETPIDREQUEST_H
#define HERO_COMMON_MESSAGE_SETPIDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hero_common
{
template <class ContainerAllocator>
struct SetPIDRequest_
{
  typedef SetPIDRequest_<ContainerAllocator> Type;

  SetPIDRequest_()
    : lkp(0.0)
    , lki(0.0)
    , lkd(0.0)
    , rkp(0.0)
    , rki(0.0)
    , rkd(0.0)  {
    }
  SetPIDRequest_(const ContainerAllocator& _alloc)
    : lkp(0.0)
    , lki(0.0)
    , lkd(0.0)
    , rkp(0.0)
    , rki(0.0)
    , rkd(0.0)  {
  (void)_alloc;
    }



   typedef float _lkp_type;
  _lkp_type lkp;

   typedef float _lki_type;
  _lki_type lki;

   typedef float _lkd_type;
  _lkd_type lkd;

   typedef float _rkp_type;
  _rkp_type rkp;

   typedef float _rki_type;
  _rki_type rki;

   typedef float _rkd_type;
  _rkd_type rkd;





  typedef boost::shared_ptr< ::hero_common::SetPIDRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hero_common::SetPIDRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPIDRequest_

typedef ::hero_common::SetPIDRequest_<std::allocator<void> > SetPIDRequest;

typedef boost::shared_ptr< ::hero_common::SetPIDRequest > SetPIDRequestPtr;
typedef boost::shared_ptr< ::hero_common::SetPIDRequest const> SetPIDRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hero_common::SetPIDRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hero_common::SetPIDRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hero_common::SetPIDRequest_<ContainerAllocator1> & lhs, const ::hero_common::SetPIDRequest_<ContainerAllocator2> & rhs)
{
  return lhs.lkp == rhs.lkp &&
    lhs.lki == rhs.lki &&
    lhs.lkd == rhs.lkd &&
    lhs.rkp == rhs.rkp &&
    lhs.rki == rhs.rki &&
    lhs.rkd == rhs.rkd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hero_common::SetPIDRequest_<ContainerAllocator1> & lhs, const ::hero_common::SetPIDRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hero_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hero_common::SetPIDRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_common::SetPIDRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_common::SetPIDRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_common::SetPIDRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_common::SetPIDRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_common::SetPIDRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hero_common::SetPIDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0d0bdba02bc62a48d52638e38dc8a4b";
  }

  static const char* value(const ::hero_common::SetPIDRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0d0bdba02bc62a4ULL;
  static const uint64_t static_value2 = 0x8d52638e38dc8a4bULL;
};

template<class ContainerAllocator>
struct DataType< ::hero_common::SetPIDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hero_common/SetPIDRequest";
  }

  static const char* value(const ::hero_common::SetPIDRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hero_common::SetPIDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 lkp # proportional term left motor\n"
"float32 lki # intergrative term left motor\n"
"float32 lkd # derivative term left motor\n"
"float32 rkp # proportional term right motor\n"
"float32 rki # intergrative term right motor\n"
"float32 rkd # derivative term right motor\n"
;
  }

  static const char* value(const ::hero_common::SetPIDRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hero_common::SetPIDRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lkp);
      stream.next(m.lki);
      stream.next(m.lkd);
      stream.next(m.rkp);
      stream.next(m.rki);
      stream.next(m.rkd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPIDRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hero_common::SetPIDRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hero_common::SetPIDRequest_<ContainerAllocator>& v)
  {
    s << indent << "lkp: ";
    Printer<float>::stream(s, indent + "  ", v.lkp);
    s << indent << "lki: ";
    Printer<float>::stream(s, indent + "  ", v.lki);
    s << indent << "lkd: ";
    Printer<float>::stream(s, indent + "  ", v.lkd);
    s << indent << "rkp: ";
    Printer<float>::stream(s, indent + "  ", v.rkp);
    s << indent << "rki: ";
    Printer<float>::stream(s, indent + "  ", v.rki);
    s << indent << "rkd: ";
    Printer<float>::stream(s, indent + "  ", v.rkd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERO_COMMON_MESSAGE_SETPIDREQUEST_H
