// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwarmBackend.Entities;
using SwarmBackend.Helpers;

#nullable disable

namespace SwarmBackend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260720185302_AddCanonicalAccountEmail")]
    partial class AddCanonicalAccountEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "sensor_type_enum", new[] { "none", "speed", "laser_distance", "encoder", "inercial", "motor_speed_percentage" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "task_type_enum", new[] { "none", "transport", "follow_leader", "formation" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SwarmBackend.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("lower(btrim(\"Email\", ' ' || chr(9) || chr(10) || chr(11) || chr(12) || chr(13)))", true);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordReset")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Verified")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Accounts", t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_Email_SupportedFormat", "char_length(btrim(\"Email\", ' ' || chr(9) || chr(10) || chr(11) || chr(12) || chr(13))) BETWEEN 1 AND 254 AND btrim(\"Email\", ' ' || chr(9) || chr(10) || chr(11) || chr(12) || chr(13)) ~ '^[A-Za-z0-9._%+-]+@([A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\.)+[A-Za-z]{2,63}$'");
                        });
                });

            modelBuilder.Entity("SwarmBackend.Entities.ComputeWorker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActiveSessionsReportedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<JsonDocument>("Capabilities")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CredentialCreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CredentialHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CredentialRevokedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DrainLeaseExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DrainLeaseId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DrainRequestedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DrainTargetRevision")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ImageVersion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MaxConcurrentSessions")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ReportedActiveSessionCount")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DrainLeaseId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("State", "LastHeartbeatAt");

                    b.ToTable("ComputeWorkers");
                });

            modelBuilder.Entity("SwarmBackend.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SwarmBackend.Entities.Robot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Namespace")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("RobotGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TaskLogId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RobotGroupId");

                    b.HasIndex("TaskLogId");

                    b.ToTable("Robots");
                });

            modelBuilder.Entity("SwarmBackend.Entities.RobotGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RobotGroups");
                });

            modelBuilder.Entity("SwarmBackend.Entities.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("RobotId")
                        .HasColumnType("integer");

                    b.Property<SensorTypeEnum>("SensorType")
                        .HasColumnType("sensor_type_enum");

                    b.HasKey("Id");

                    b.HasIndex("RobotId");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("SwarmBackend.Entities.SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("SwarmBackend.Entities.SessionRobot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RuntimeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SimulationSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SimulationSessionId", "Namespace")
                        .IsUnique();

                    b.HasIndex("SimulationSessionId", "Ordinal")
                        .IsUnique();

                    b.HasIndex("SimulationSessionId", "RuntimeId")
                        .IsUnique();

                    b.ToTable("SessionRobots");
                });

            modelBuilder.Entity("SwarmBackend.Entities.SimulationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("ArenaVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ComputeWorkerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DesiredRobotCount")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsEmergencyStopped")
                        .HasColumnType("boolean");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StoppedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WorkerImageVersion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasFilter("\"State\" < 6");

                    b.HasIndex("ComputeWorkerId");

                    b.HasIndex("State", "CreatedAt", "Id");

                    b.ToTable("SimulationSessions", t =>
                        {
                            t.HasCheckConstraint("CK_SimulationSessions_DesiredRobotCount_Positive", "\"DesiredRobotCount\" > 0");
                        });
                });

            modelBuilder.Entity("SwarmBackend.Entities.TaskLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateCancelled")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateFinished")
                        .HasColumnType("timestamp without time zone");

                    b.Property<JsonDocument>("Parameters")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("RobotGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RobotGroupId");

                    b.HasIndex("TaskTemplateId");

                    b.ToTable("TaskLogs");
                });

            modelBuilder.Entity("SwarmBackend.Entities.TaskRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CommandRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("LastProgressAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastReportAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OutcomeReason")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("OutcomeState")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("Parameters")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("Progress")
                        .HasColumnType("double precision");

                    b.Property<JsonDocument>("Result")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SimulationSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("State")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SimulationSessionId", "CreatedAt");

                    b.HasIndex("State", "LastProgressAt");

                    b.ToTable("TaskRuns", t =>
                        {
                            t.HasCheckConstraint("CK_TaskRuns_Progress_Range", "\"Progress\" >= 0 AND \"Progress\" <= 1");
                        });
                });

            modelBuilder.Entity("SwarmBackend.Entities.TaskTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TaskType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TaskTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Enabled = true,
                            Name = "One",
                            TaskType = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Enabled = true,
                            Name = "One",
                            TaskType = 1
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Enabled = true,
                            Name = "Two",
                            TaskType = 2
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Enabled = true,
                            Name = "Third",
                            TaskType = 3
                        });
                });

            modelBuilder.Entity("SwarmBackend.Entities.ViewerLease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PublishTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RobotRuntimeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SimulationSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PublishTokenHash")
                        .IsUnique();

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("SimulationSessionId", "ExpiresAt");

                    b.HasIndex("SimulationSessionId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("ViewerLeases");
                });

            modelBuilder.Entity("SwarmBackend.Entities.WorkerCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ComputeWorkerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("Result")
                        .HasColumnType("jsonb");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SimulationSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<Guid?>("TaskRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ComputeWorkerId");

                    b.HasIndex("TaskRunId");

                    b.HasIndex("SimulationSessionId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("SimulationSessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("WorkerCommands");
                });

            modelBuilder.Entity("SwarmBackend.Entities.RefreshToken", b =>
                {
                    b.HasOne("SwarmBackend.Entities.Account", "Account")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SwarmBackend.Entities.Robot", b =>
                {
                    b.HasOne("SwarmBackend.Entities.Account", "Account")
                        .WithMany("Robots")
                        .HasForeignKey("AccountId");

                    b.HasOne("SwarmBackend.Entities.RobotGroup", "RobotGroup")
                        .WithMany("Robots")
                        .HasForeignKey("RobotGroupId");

                    b.HasOne("SwarmBackend.Entities.TaskLog", null)
                        .WithMany("Robots")
                        .HasForeignKey("TaskLogId");

                    b.Navigation("Account");

                    b.Navigation("RobotGroup");
                });

            modelBuilder.Entity("SwarmBackend.Entities.Sensor", b =>
                {
                    b.HasOne("SwarmBackend.Entities.Robot", "Robot")
                        .WithMany("Sensors")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("SwarmBackend.Entities.SensorReading", b =>
                {
                    b.HasOne("SwarmBackend.Entities.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SwarmBackend.Entities.SessionRobot", b =>
                {
                    b.HasOne("SwarmBackend.Entities.SimulationSession", "SimulationSession")
                        .WithMany("Robots")
                        .HasForeignKey("SimulationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationSession");
                });

            modelBuilder.Entity("SwarmBackend.Entities.SimulationSession", b =>
                {
                    b.HasOne("SwarmBackend.Entities.Account", "Account")
                        .WithMany("SimulationSessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SwarmBackend.Entities.ComputeWorker", "ComputeWorker")
                        .WithMany("Sessions")
                        .HasForeignKey("ComputeWorkerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("ComputeWorker");
                });

            modelBuilder.Entity("SwarmBackend.Entities.TaskLog", b =>
                {
                    b.HasOne("SwarmBackend.Entities.RobotGroup", null)
                        .WithMany("TaskLogs")
                        .HasForeignKey("RobotGroupId");

                    b.HasOne("SwarmBackend.Entities.TaskTemplate", "TaskTemplate")
                        .WithMany()
                        .HasForeignKey("TaskTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskTemplate");
                });

            modelBuilder.Entity("SwarmBackend.Entities.TaskRun", b =>
                {
                    b.HasOne("SwarmBackend.Entities.SimulationSession", "SimulationSession")
                        .WithMany("TaskRuns")
                        .HasForeignKey("SimulationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationSession");
                });

            modelBuilder.Entity("SwarmBackend.Entities.ViewerLease", b =>
                {
                    b.HasOne("SwarmBackend.Entities.Account", "Account")
                        .WithMany("ViewerLeases")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SwarmBackend.Entities.SimulationSession", "SimulationSession")
                        .WithMany("ViewerLeases")
                        .HasForeignKey("SimulationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("SimulationSession");
                });

            modelBuilder.Entity("SwarmBackend.Entities.WorkerCommand", b =>
                {
                    b.HasOne("SwarmBackend.Entities.ComputeWorker", "ComputeWorker")
                        .WithMany("Commands")
                        .HasForeignKey("ComputeWorkerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SwarmBackend.Entities.SimulationSession", "SimulationSession")
                        .WithMany("Commands")
                        .HasForeignKey("SimulationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwarmBackend.Entities.TaskRun", "TaskRun")
                        .WithMany("Commands")
                        .HasForeignKey("TaskRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ComputeWorker");

                    b.Navigation("SimulationSession");

                    b.Navigation("TaskRun");
                });

            modelBuilder.Entity("SwarmBackend.Entities.Account", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Robots");

                    b.Navigation("SimulationSessions");

                    b.Navigation("ViewerLeases");
                });

            modelBuilder.Entity("SwarmBackend.Entities.ComputeWorker", b =>
                {
                    b.Navigation("Commands");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("SwarmBackend.Entities.Robot", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("SwarmBackend.Entities.RobotGroup", b =>
                {
                    b.Navigation("Robots");

                    b.Navigation("TaskLogs");
                });

            modelBuilder.Entity("SwarmBackend.Entities.SimulationSession", b =>
                {
                    b.Navigation("Commands");

                    b.Navigation("Robots");

                    b.Navigation("TaskRuns");

                    b.Navigation("ViewerLeases");
                });

            modelBuilder.Entity("SwarmBackend.Entities.TaskLog", b =>
                {
                    b.Navigation("Robots");
                });

            modelBuilder.Entity("SwarmBackend.Entities.TaskRun", b =>
                {
                    b.Navigation("Commands");
                });
#pragma warning restore 612, 618
        }
    }
}
