# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hero_common/Encoder.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Encoder(genpy.Message):
  _md5sum = "b5586cdbae9b740afc6a1f403a2d7dde"
  _type = "hero_common/Encoder"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

float64 left_ticks
float64 right_ticks
float64 left_diff
float64 right_diff
float64 left_dist
float64 right_dist
float64 timestep
float64 left_speed
float64 right_speed
float64 left_speed_filtered
float64 right_speed_filtered
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','left_ticks','right_ticks','left_diff','right_diff','left_dist','right_dist','timestep','left_speed','right_speed','left_speed_filtered','right_speed_filtered']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,left_ticks,right_ticks,left_diff,right_diff,left_dist,right_dist,timestep,left_speed,right_speed,left_speed_filtered,right_speed_filtered

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Encoder, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left_ticks is None:
        self.left_ticks = 0.
      if self.right_ticks is None:
        self.right_ticks = 0.
      if self.left_diff is None:
        self.left_diff = 0.
      if self.right_diff is None:
        self.right_diff = 0.
      if self.left_dist is None:
        self.left_dist = 0.
      if self.right_dist is None:
        self.right_dist = 0.
      if self.timestep is None:
        self.timestep = 0.
      if self.left_speed is None:
        self.left_speed = 0.
      if self.right_speed is None:
        self.right_speed = 0.
      if self.left_speed_filtered is None:
        self.left_speed_filtered = 0.
      if self.right_speed_filtered is None:
        self.right_speed_filtered = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.left_ticks = 0.
      self.right_ticks = 0.
      self.left_diff = 0.
      self.right_diff = 0.
      self.left_dist = 0.
      self.right_dist = 0.
      self.timestep = 0.
      self.left_speed = 0.
      self.right_speed = 0.
      self.left_speed_filtered = 0.
      self.right_speed_filtered = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_11d().pack(_x.left_ticks, _x.right_ticks, _x.left_diff, _x.right_diff, _x.left_dist, _x.right_dist, _x.timestep, _x.left_speed, _x.right_speed, _x.left_speed_filtered, _x.right_speed_filtered))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 88
      (_x.left_ticks, _x.right_ticks, _x.left_diff, _x.right_diff, _x.left_dist, _x.right_dist, _x.timestep, _x.left_speed, _x.right_speed, _x.left_speed_filtered, _x.right_speed_filtered,) = _get_struct_11d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_11d().pack(_x.left_ticks, _x.right_ticks, _x.left_diff, _x.right_diff, _x.left_dist, _x.right_dist, _x.timestep, _x.left_speed, _x.right_speed, _x.left_speed_filtered, _x.right_speed_filtered))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 88
      (_x.left_ticks, _x.right_ticks, _x.left_diff, _x.right_diff, _x.left_dist, _x.right_dist, _x.timestep, _x.left_speed, _x.right_speed, _x.left_speed_filtered, _x.right_speed_filtered,) = _get_struct_11d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_11d = None
def _get_struct_11d():
    global _struct_11d
    if _struct_11d is None:
        _struct_11d = struct.Struct("<11d")
    return _struct_11d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
